---
service_lifecycle_case_1:
  desc: basic service lifecycle stress testing
  application:
    name: "worker"
    framework: "sinatra"
    runtime: "ruby19"
    memory: 1024
    services:
      tested_inst:
        name: mysql
        provider: core
        plan: free
        version: "5.1"

  cusers: 2

  preload:
    desc: preload some data, size(MB), max size is 5 MB
    loop: 1
    thinktime: 5
    load:
      crequests: 5
      size: 0.02
      loop: 2
      thinktime: 5

  take_snapshot:
    desc: load data and then take snapshot, data(MB)
    loop: 3
    thinktime: 5
    load:
      desc: load data
      crequests: 10
      size: 0.1
      loop: 3
      thinktime: 5

  rollback:
    desc: random select one snapshot from take_snapshot session. test import from url and import from data
    loop: 3
    thinktime: 5
    load:
      desc: load data
      crequests: 3
      size: 0.3
      loop: 10
      thinktime: 5
    import_from_url: true
    import_from_data: true

  unprovision: false



