---
service_lifecycle_case_1:
  desc: basic service lifecycle stress testing
  application:
    name: "worker"
    framework: "sinatra"
    runtime: "ruby19"
    memory: 256
    services:
      tested_inst:
        name: mysql
        provider: core
        plan: free
        version: "5.1"

  cusers: 10

  preload:
    desc: preload some data, data(MB)
    load:
      crequests: 2
      data: 0.1
      loop: 5
      thinktime: 2

  take_snapshot:
    desc: load data and then take snapshot, data(MB)
    loop: 10
    load:
      desc: load data
      crequests: 10
      data: 1
      loop: 10
      thinktime: 2

  rollback:
    desc: random select one snapshot from take_snapshot session. test import from url and import from data
    loop: 100
    load:
      desc: load data
      crequests: 10
      data: 1
      loop: 10
      thinktime: 2
    import_from_url: true
    import_from_data: true

  unprovision: false



